"""Add location, industry, and blurb to User model

Revision ID: 69481e39dba0
Revises: f79ebca561a0
Create Date: 2024-10-29 17:30:17.244590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69481e39dba0'
down_revision = 'f79ebca561a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_industry',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'industry_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('blurb', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('blurb')
        batch_op.drop_column('location')

    op.drop_table('user_industry')
    op.drop_table('industry')
    # ### end Alembic commands ###
