"""Add profile_icon_id to Mentor model

Revision ID: 747c962afaf2
Revises: a1486b43c792
Create Date: 2025-02-26 13:01:24.004563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747c962afaf2'
down_revision = 'a1486b43c792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_icon_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor', schema=None) as batch_op:
        batch_op.drop_column('profile_icon_id')

    # ### end Alembic commands ###
