"""Add linkedin column to mentor table

Revision ID: 8a5a2c18be77
Revises: 8af417333b14
Create Date: 2025-01-07 17:16:41.779806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5a2c18be77'
down_revision = '8af417333b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('expertise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expertise_id'], ['expertise.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor', schema=None) as batch_op:
        batch_op.drop_column('linkedin')

    op.drop_table('mentor_needs')
    # ### end Alembic commands ###
