"""Add mentor_expertise association table

Revision ID: f79ebca561a0
Revises: fdbca4755d25
Create Date: 2024-10-29 17:27:13.433286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79ebca561a0'
down_revision = 'fdbca4755d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_expertise',
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('expertise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expertise_id'], ['expertise.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('mentor_id', 'expertise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentor_expertise')
    # ### end Alembic commands ###
